name: Build and Publish Docker Image
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: Build Container
        run: |
          docker build -t smart-device-relay:latest .
          docker tag smart-device-relay:latest ghcr.io/migeorge/smart-device-relay:${{ github.sha }}
          docker tag smart-device-relay:latest ghcr.io/migeorge/smart-device-relay:latest
      
      - name: Push to GHCR
        run: |
          docker push ghcr.io/migeorge/smart-device-relay:${{ github.sha }}
          docker push ghcr.io/migeorge/smart-device-relay:latest